### ISSUE TITLE
listJobs doesn't work with a read-only API key

### ISSUE THREAD

**Issue by ftrofin** [zencoder/zencoder-java#15]
Hello,

If I use a read-only API key with listJobs() it doesn't work. This is very unfortunate because it forces me to use a full access key in a context where I'm only doing read-only operations. This violates the principle of least privilege and is a security issue. Please fix this!

com.brightcove.zencoder.client.ZencoderClientException: {"errors":["api_key is read only"]}
at com.brightcove.zencoder.client.ZencoderClient.listJobs(ZencoderClient.java:212)

Thanks!

Florin

**Comment by skidder** [comment]
Hi Florin,

This is consistent with the expected behavior of the Zencoder API.  The set of operations that can be invoked with read-only API keys is detailed here:
https://app.zencoder.com/docs/guides/advanced-integration/read-only-api-keys-and-jsonp

Read-only API keys are often used in untrusted or less-trusted applications that might be interested in the status of a single job or set of jobs.  If the `listJobs` operation were allowed with read-only API keys then it would be possible for these less-trusted applications to discover all jobs within the account, which could be bad.

I hope this answers your question, please let me know if I can be of additional help.
